#!/bin/bash

set -e

if [[ -n "${STACTOOLS_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run a jupyter notebook server in a docker container with all prerequisites installed.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    docker run --rm -it \
        -v "$(pwd)":/opt/stactools-noaa-hrrr \
        -p 8000:8000 \
        --entrypoint /bin/bash \
        stactools-packages/noaa-hrrr:dev \
        -c "source /opt/conda/bin/activate && source /opt/venv/bin/activate && jupyter lab --ip=0.0.0.0 --port=8000 --no-browser --allow-root"
fi
