#!/usr/bin/env python

import logging
from pathlib import Path

from stactools.noaa_hrrr.inventory import generate_inventory_csv_gzs

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler("/tmp/noaa_hrrr_generate_inventory.log"),
        logging.StreamHandler(),
    ],
)

logger = logging.getLogger(__name__)

root = Path(__file__).parents[1]
data_dir = root / "src" / "stactools" / "noaa_hrrr" / "data"

generate_inventory_csv_gzs(data_dir)
